#!/bin/sh
#
# This script sets the environment variables without having to
# modify login profile.
#
# Usage:
#   vr-wrapper ~/.vrw/runners [COMMAND] 
#
# Example profile ~/.vrw/runners:
#
#   #!/bin/bash
#   export PATH="/nfs/users/nfs_p/pd3/git/vr-runner/scripts:$PATH"
#   export PERL5LIB="/nfs/users/nfs_p/pd3/git/vr-runner/modules:$PERL5LIB"
#

function usage()
{
    echo "Usage: vr-wrapper [OPTIONS] [PROFILE] cmd"
    echo "Options:"
    echo "    -e      No shell expansion, use exec instead of eval"
    echo "    -h      This help message"
    echo "Examples:"
    echo "    vr-wrapper - 'set > variables.txt'"
    echo "    vr-wrapper /path/to/optional/profile 'set > variables.txt'"
    echo "    vr-wrapper -e ~/.vrw/local printf 'hello world!\n'"
    exit 1
}

if [ $# -eq 0 -o "$1" == '-h' ]; then 
    usage
fi

cmd="eval"
if [ "$1" == '-e' ]; then
    cmd="exec"
    shift 1
fi

if [ "$1" != '-' ]; then 
    . $1
fi
umask 007

shift 1
$cmd "$@"

